README.md
Canvas er jo også en tag i HTML5. Ved å legge en lenke til Canvas/Instructure blir det tydeligere hva det er snakk om.
=> Hyperlenke til Canvas

src/js/3party/uob7.js
Commented out the code that disables forgotten password link.
=> Forgotten password link was disabled by uob.js

package.json, spec/groups_spec.js, src/js/main.js, src/js/modules/coursepage.js, src/js/modules/groups.js, src/js/modules/menu.js
Updates design to conform to design spec for groups.
=> [MAT-187] Oppdatere design for grupper til globale grupper

src/js/api/api.js, src/js/modules/adminfunctions.js, src/js/modules/powerfunctions.js, src/templates/modules/powerfunctions/headteacher.hbs, src/templates/modules/powerfunctions/mainteacher.hbs
Instead, courses that the teacher has access to are listed directly.
Move admin specific functions into separate adminfunctions.js file.
powerfunctions.js and adminfunctions.js should be refactored at a later stage.
=> Remove account picking for mmpf since teachers cannot access accounts.

src/js/modules/pages.js, src/js/modules/powerfunctions.js, src/templates/modules/powerfunctions/mainteacher.hbs
The problem of the missing "Save comments" button has also been reported by another user in the Canvas community: https://community.canvaslms.com/thread/12681
Also, a user in the facebook group "Canvs expert group" has experience this problem.
=> MAT-307 Enable code from Leif that adds missing "Save comments" button in rubric

.gitignore, src/js/i18n.js, src/js/main.js, src/js/modules/coursepage.js, src/js/modules/enroll.js, src/js/modules/template.js, src/js/settings.js, src/templates/modules/allcourseslist.hbs
Tickets: 
https://netguru.atlassian.net/browse/UDIR-115
https://netguru.atlassian.net/browse/UDIR-107
Changes:
- links added to every category and course on /search/all_courses
- links redirects to /search/all_courses and specific course in the list
- animation after redirection and opening the deep link to a course
- accessing a course without being logged: button redirects to /search/all_courses and string in the button is moved to i18n.js
- the feature works also on mobile
=> [UDIR-115] - linking to specific course in the courses list

.gitignore, src/css/pages/canvas-login.less
Ticket: https://netguru.atlassian.net/browse/UDIR-108
Changes:
- the logo is now visible in the logout dialog box
=> [UDIR-108] - logout dialog box

.gitignore, src/css/framework/canvas-footer-newui.less
Previous/next arrows in footer buttons fixed.
https://netguru.atlassian.net/browse/UDIR-109
=> [UDIR-109] - previous/next buttons are missing arrows

.gitignore, src/css/modules/allcourseslist.less, src/js/main.js, src/js/modules/enroll.js, src/templates/modules/allcoursescontainer.hbs
Ticket: https://netguru.atlassian.net/browse/UDIR-106
Changes: 
New button in https://localhost/search/all_courses?design=udir that takes to https://localhost/courses?design=udir with proper color
=> [UDIR-106 - new button in available subjects

.gitignore, package.json, yarn.lock
Ticket: https://netguru.atlassian.net/browse/UDIR-118
Dependency 'tar fs' updated to new version
=> [UDIR-118] - warning message

src/js/main.js, src/js/modules/discussion-topics.js, src/js/modules/tinyMCEEditor.js
Add hashtags to group discussions, correctly recognize tags with escaped characters. KURSP-85
=> Add hashtags to group discussions, fix tag recognition

src/css/framework/canvas-header.less
=> KURSP-202 finhsed cleaning dead code.

src/js/3party/GA-script-v2.js
=> GA tag manager v.2

src/templates/modules/moduleitems.hbs, src/templates/modules/moduleitemsprincipal.hbs
=> Add missing multilang translate class to html elements

src/js/api/api.js, src/js/main.js
Changes to api.js is to simplify a needlessly complex function.
=> Fix group discussion hashtags

kpas/kpas.html, kpas/main.js, src/js/3party/kpas.js, src/js/main.js, src/js/settings.js
Sjekk at statistikk virker som det skal både for leder og for faglærer/admin. Faglærer/admin skal få opp et nummerfelt der hun kan oppgi fylkenummer/kommunenummer og deretter trykke oppdater. Da vises statistikken for det fylket/den kommunen.
=> La faglærer/admin velge fylke/kommune i statistikken.

src/js/3party/gtm_v6_head.js
=> analytics_integration_105

src/js/3party/analytics_integration.js
analytics file added. re 105 issue
=> added analytics file

src/css/framework/canvas-header.less, src/css/modules/accordion.less, src/css/modules/loginPopup.less, src/css/modules/noLoggedInHeader.less, src/css/modules/tabs.less, src/css/modules/usermenu-newui.less, src/css/setup/variables.less, src/js/modules/menu.js, src/js/rootaccount.js, src/templates/modules/noLoggedInHeaderMobile.hbs
Første runde. Toppmenylinja skal nå vises riktig uansett skjermstørrelse.
=> Support small screens.

src/css/allrootaccount.less, src/css/modules/loginPopup.less, src/js/modules/dataporten.js, src/js/rootaccount.js
Har endret "Har ikke Feide" til "Ikke Feide" og flyttet logoene nederst. La til "Logg på med" over knappene.
=> Kursp 398 siste finpuss innlogging

src/css/3party/vimeo.less, src/css/setup/variables.less, src/js/3party/vimeo.js, src/templates/modules/transcriptMenu.hbs
Put colors in variables file.
Add/remove class when changing hightlighted caption instead of adding/removing styles.
Remove leading and trailing dashes in captions.
Create parent elements directly in DOM instead of using innerHTML to make the immediately available (used to cause the code to fail).
Default to first language available if the users preferred language is not available.
=> Change colors to Udir palette with opacity inspired by Coursera.

package.json, yarn.lock
@erlendthune  Unsure if this actually fixes security bumps, however i did manually update all dependabot alerts, and i have no problems compiling or running grunt, or the design. Can you double check?
=> Kursp 420 dependabot update

src/css/framework/canvas-footer-newui.less, src/css/pages/canvas-pages.less, src/js/modules/pages.js
=> Kursp 427 attempt 2

Gruntfile.js, package.json, src/js/3party/uob7.js, src/js/modules/dataporten.js, src/js/modules/enroll.js, src/js/modules/util.js, src/js/settings.js, src/templates/modules/allcoursescontainer.hbs, yarn.lock
Denne versjonen viser en advarsel når brukeren bruker en mobil enhet.
=> Kursp 504 diverse utbedringer for ipad telefon

src/js/3party/multilanguage.js, src/js/modules/util.js
=> KURSP-727: nynorsk

src/js/modules/discussion-topics.js
=> KURSP-680: fix hidden label

src/js/modules/announcements.js, src/js/modules/menu.js
remove tab order fom non-active elements
=> KURSP-681: remove non activ elements from taborder

src/css/framework/canvas-framework.less
when zoomed/small screen content still readable
=> KURSP-666: fix view when zoomed

src/js/3party/vimeo.js
making transcript box focusable
=> KURSP-678: trascript box scrollable with keyboard

src/js/modules/enroll.js, src/templates/modules/allcourseslist.hbs
=> KURSP-661: unique id

src/templates/modules/noLoggedInHeader.hbs
ul children can only be li, script or templates
=> KURSP-664: ul children

src/css/3party/canvas-uob.less, src/css/framework/canvas-button.less, src/css/modules/accordion.less, src/css/modules/loginPopup.less, src/css/modules/noLoggedInHeader.less, src/css/modules/tabs.less
Make focus visible in available courses list
=> KURSP-667: Visible focus

kpas/grupper.css, src/css/3party/canvas-uob.less
kpas-lti-warning/info id several places
=> KURSP-674: unique id

src/js/3party/vimeo.js
add label to transcription language dropdown
=> KURSP-677-selector-label

src/js/3party/multilanguage.js, src/js/main.js
=> KURSP-751: Fix missing header when invalid lang in cookie

src/js/3party/h5piframeresizer.js, src/js/3party/kpas.js, src/js/3party/vimeo.js, src/js/main.js
add title to vimeo and h5p frames
=> KURSP-676: title to 3rd party iframes

src/templates/modules/coursemenu.hbs
=> KURSP-751: language select

src/css/modules/noLoggedInHeader.less
fix bug when hover login button
=> KURSP-783: login button

src/js/3party/uob7.js
Add possibility to use h5p in uob-accordian and uob-reveal
=> KURSP-32: Possibility to add h5p to uob-accordion and uob-reveal

src/js/3party/vimeo.js
expand backgroud box when opening transcription
=> KURSP-591: expand background box

src/js/main.js, src/js/modules/util.js
remove recent feedback from right menu
=> KURSP-197: remove recent feedback

src/js/modules/menu.js
Remove new buttons History, Courses, Administrator, Groups and Commons from header
=> KURSP-808: Remove new buttons from header

src/js/3party/vimeo.js
Only expand for transcript if iframe has sibling
=> KURSP-812: Transcript box

src/js/modules/menu.js
add nullcheck before removing buttons from header
=> KURSP-813: add nullcheck before removing buttons

src/js/modules/menu.js
Remove commons header button for teachers and admins
=> KURSP-813: remove commons for teachers

src/js/modules/menu.js, src/js/modules/util.js, src/js/rootaccount.js
Make module menu in course pages visible to users, fix conflic between sub and root account
=> KURSP-852: Module menu and double header and footer as student

src/js/3party/uob7.js
Possiblilty to load h5p inside uob-tabs
=> KURSP-858: H5P inside uob-tabs

webpack.production.config.js, webpack.staging.config.js
=> KURSP-861: matomo

src/vue/design/index.scss, src/vue/design/typography.scss, webpack.dev.config.js, webpack.development.config.js
Had not yet resolved the urls for the fonts.
I believe this will be working ok, but have not yet served the dev branch.
Currently passing a sass variable to the typography file, so it gets the correct url.
It is very picky on how the url is constructed.
It appeared to be working locally as webpack picked the files locally and not from localhost. And therefore was able to compile the sass files without issues.
=> Url for getting the fonts

src/js/modules/menu.js
declear id variable for next module item
=> KURSP-873: fix next button not showing

.github/workflows/deploy-storybook.yml
This needs to be merged to dev in order to test that it works.
=> set up workflow to publish storybook on gh-pages

.github/workflows/deploy-storybook.yml
Change directory so that the app is served from storybook instead of ./story-book
=>  Kursp-884 change output dir path to render from

src/vue/.storybook/main.js, src/vue/stories/Card.stories.js
properties on components were changed, so needed to update how storybook rendered componentes. Images should now also show in storybook
=>  Kursp887:fix image paths for cards and banner

package.json, src/vue/.storybook/main.js, src/vue/components/Banner.vue, src/vue/stories/Card.stories.js, yarn.lock
Create a solution that checks if we are in frontend folder in file system. if we are, a path need to be appended to the images.
Currently when we publish storybook to gh-pages, images dont get rendered because the path is changed.
Package installed:
fs:this helps us deal with file systems to find the correct path for the images.
=> Therese persen kursp 893 update assets path so images can render correctly

src/js/modules/coursepage.js, src/js/modules/menu.js, src/js/modules/module-selector/data.js, src/js/modules/module-selector/index.js, src/js/modules/module-selector/utils.js, src/vue/components/course-modules/CourseModule.vue, src/vue/components/course-modules/CourseModuleContainer.vue, src/vue/components/course-modules/CourseModules.vue, src/vue/components/course-modules/index.js, src/vue/components/tree-view/TreeView.vue
1. Fetching data for each module
2. add data to the module-selector
3. attach the module selector to the dom
4. delete code that is interfering and that will not be used in the future
=> Therese persen kursp 909 module selector fetch data and reformat so it fits into the module selector

src/vue/components/course-page-banner/CoursePageBanner.stories.js, src/vue/components/course-page-banner/CoursePageBanner.vue
=> KURSP-919-Create course page banner

src/js/main.js, src/vue/components/course-modules/CourseModule.vue, src/vue/design/override-base-Canvas-elements.scss
Override base elements in Canvas to fit custom components in view
=> KURSP-916: Component placements

src/js/modules/announcements/data.js, src/js/modules/announcements/index.js, src/vue/components/announcements/Announcements-container.vue, src/vue/components/announcements/announcements.stories.js, src/vue/components/announcements/announcements.vue, src/vue/components/announcements/index.js, src/vue/components/course-modules/CourseModuleContainer.vue, src/vue/components/course-modules/index.js
Adding the announcements link to the course page,
=> KURSP-926: add announcements link on the course page

src/vue/components/announcements/announcements.vue
Missing styles in previous merge, that I had accidentally deleted.
=> applying style changes that were missing

src/js/modules/next-prev-buttons.js
Set button order prior to loading vue components
=> KURSP-936: race condition nav buttons

src/js/main.js, src/js/modules/pages.js
Remove items in student view:
- Header on the coursepage
- Admin menu on the left side below module selector:
=> KURSP-928: remove items from course page, that is not needed in student view

src/js/modules/module-selector/utils.js, src/vue/components/course-modules/CourseModule.vue, src/vue/components/course-modules/CourseModules.vue, src/vue/components/course-modules/test-data.js, src/vue/components/tree-view/TreeView.vue
Show selected page on the module selector.
Update storybook story and dummy data so that it is compatible with the new changes
=> Kursp 938 module selector navigation

service-worker.js, src/vue/components/course-modules/CourseModuleContainer.vue
Create service worker.
Add the service worker to the dom through the coursemodulescontainer
=> Kursp 945 cache request module selector

src/js/modules/coursepagebanner.js, src/vue/components/course-page-banner/CoursePageBanner.stories.js, src/vue/components/course-page-banner/CoursePageBanner.vue, src/vue/components/dropdown-button/DropdownButton.stories.js, src/vue/components/dropdown-button/DropdownButton.vue, src/vue/components/language-selector-container/LanguageSelectorContainer.vue, src/vue/components/language-selector-container/index.js, src/vue/components/language-selector-container/util.js, src/vue/utils/lang-utils.js, src/vue/utils/previous-lang-utils.js
1. Use settings from kpas to find available languages to render in the banner.
2. If there is only bokmål, do not render the button.
3. Update component to use the language utility functions,
4. Update storybook stories, so they do not break.
5. Remove code that is clashing with current implementation i langutils.
6. Add parent components to handle logic inside the app, that can not be dealt with in storybook
7. set the url correctly when the language is selected.
=> Kursp 949 implementer sprak valg knapp

src/vue/components/course-modules/CourseModule.vue, src/vue/components/course-modules/CourseModuleContainer.vue, src/vue/components/course-modules/CourseModules.vue, src/vue/components/tree-view/TreeView.vue
Add Observable  library.
Observe changes to url.
pass language to child components.
Language is updated in language selector whenever the user changes the language, without reload.
=> Kursp 951 lang select update module selector

src/vue/components/announcements/Announcements-container.vue, src/vue/components/announcements/Announcements.vue, src/vue/components/course-modules/CourseModuleContainer.vue, src/vue/components/course-modules/CourseModules.vue, src/vue/components/course-modules/completed-utils.js, src/vue/components/module-progress-indicator/ModulesProgressIndicator.stories.js, src/vue/components/module-progress-indicator/ModulesProgressIndicator.vue, src/vue/components/tree-view/TreeView.vue, src/vue/pages/course-page/left-menu/CoursePageLeftSideView.vue
Add progression indicator,
Make module selector smaller in width.
=> Kursp 837 progression done course

src/vue/utils/lang-utils.js, src/vue/utils/previous-lang-utils.js
Fix bug when accessing a course with a multilang cookie that does not exists for current course
=> KURSP-996: Multilang when only two languages

src/js/modules/tabs.js
if (celltext == "[uob-tabs]" || celltext == "[uob-tabs]")
=> KURSP-1021 pick up the new tag [udir-tabs]

src/js/modules/accordion.js
=> KURSP-1019-rename-accordion-udir

src/vue/design/accordion.scss, src/vue/design/re-styles/tabs.scss
change the color variables to use the sass variables.
=> KURSP-1029-fix-css for accordion and tabs

src/js/modules/menu-utils.js, src/js/modules/menu.js, src/vue/components/CardList.vue, src/vue/components/header/NavBar.vue, src/vue/components/modal/Modal.vue, src/vue/pages/LoggedInLandingPage.vue, src/vue/pages/MyCoursesPage.vue
Add the option to skip navigation
=> Add option for tabbing to skip to main content

src/js/modules/infoboxes.js
Add tag name udir-info, for informationboxes(uthevingsbokser)
=> KURSP-1036 udir-info is added to infoboxes

webpack.production.config.js
Added changes to formating in webpack file for production. It is now in line with the working theme of dev.
=> KURSP-1065

README.md
Changed line i readme to push new action
=> KURSP-1065-Wuff

.github/workflows/build-dev-push-azure.yml, .github/workflows/build-master-push-azure.yml, .github/workflows/deploy-storybook.yml
- Update node version from 16 -> 20 according to github
depreciation
- For consistency change the use of npm to yarn
=> FIX: Update workflow files

src/vue/components/course-modules/CourseModule.vue, src/vue/components/course-modules/CourseModules.vue, src/vue/components/icon-button/IconButton.vue, src/vue/components/modal/Modal.vue, src/vue/components/tree-view/TreeView.vue, webpack.dev.config.js, webpack.production.config.js
…needed, already in default vue
=> KURSP-1165: Fix build warnings

src/vue/components/Card.vue, src/vue/components/CardHighlighted.vue, src/vue/components/CardList.vue, src/vue/components/NotLoggedInIntro.vue
- Updated: Card item to include filter options from course settings as tags.
- Updated: Card container to support dynamic height scalling instead of a hardcoded value, since tags could lead to unpredictable height values
=> DIT-124: Added tags to cards

src/js/main.js, src/js/modules/coursepagebanner.js, src/js/modules/util.js, src/vue/components/course-page-banner/CoursePageBanner.vue, src/vue/components/modal/Modal.vue, src/vue/components/unenroll/UnenrollCourse.vue, src/vue/utils/url-utils.js
- Bugfix: Unenrollment goes to 404 page after click inside default modal button from Canvas
- Updated: Course banner to include custom unenrollment modal
Added: Custom unenrollment modal handled by Vue instead of Canvas
Added: Util to get cookie
=> DIT-235: Added custom modal for self unenrollment

src/js/modules/enroll.js, src/vue/components/Card.vue, src/vue/components/CardList.vue, src/vue/components/CircularProgressBar.vue
- Added: New component for circular progress bar
- Updated: Card to show course progress
- Updated: Enroll page with include course progress to frontpage view
=> DIT-130: Add course progress to cards

src/vue/components/course-modules/page-navigation/PageNavigationButtonLinks.vue, src/vue/design/override-mobile.scss
The "Forrige" and "Neste" buttons was not properly aligned
in the mobile view, this commit makes it usable on smaller screens.
=> DIT-46: Change "Forrige" and "Neste" button to fit mobile view

src/vue/components/Button.vue, src/vue/components/Card.vue, src/vue/components/CardList.vue, src/vue/components/NotLoggedInIntro.vue, src/vue/components/login-choice/RegisterChoice.vue, src/vue/design/override-mobile.scss
- Realigned buttons on cards across cards on MyCourses, AllCourses and LoggedOut pages.
=> DIT-238: Buttonsizes

src/vue/design/override-base-Canvas-elements.scss
=> DIT-355: Navigation

src/vue/design/re-styles/tabs.scss
- Fixed overflow issue
- Aligned title to header correctly
- Added borders to tabs-view
- Realigned content
=> DIT-346: Tabs

src/vue/design/_infoboxes.scss
* Fixed size issue for infoboxes
=> DIT-353/DIT-344: Infoboxes

src/vue/design/accordion.scss
- Fixed issue with tablecells having set-height not responsive to content.
=> DIT-343: Accordions.

src/js/modules/reveal.js, src/vue/design/reveal.scss, yarn.lock
- Changed button alignment and size
- Made button and content responsive
- Fixed overflow issue of content
¨
=> DIT-203: Reveal

src/vue/design/override-mobile.scss, src/vue/design/re-styles/tooltip.scss
* Fixed overflow issue for lists
* FIxed positioning issue for hint boxes
* Changed design slightly to better differentiate from background
* Added shadow to box to differentiate from background
* Made hints responsively follow position of explained word
* Fixed issue with hint buttontext overlapping hint text
=> DIT-246: Hints.

src/vue/components/Banner.vue, src/vue/design/_infoboxes.scss
- Introduced word break to make text stay inside containers
=> DIT-375: Banner overflow.

src/js/account-theme.js
-Login screen for mobile now displays correctly
=> DIT-149: Mobilelogin

src/js/modules/tooltip.js, src/vue/design/re-styles/tooltip.scss
- Fixed issue with container element
=> DIT-246: Hints

src/vue/design/override-login-logout-Canvas-elements.scss
- Changed design to fit with other boxes of same style
- Fixed issues with overflow.
- Realigned Items and removed certain superfluous text strings
=> DIT-253: Enrolloggedout.

src/vue/components/Card.vue
- Fixed issue with text not breaking causing overflow
=> DIT-418: CardProgression.

src/vue/design/override-mobile.scss
- Fixed issue with cramped buttons on smaller screens.
=> DIT-419: CardButtons.

src/vue/pages/MyCoursesPage.vue
=> DIT-447: Centering

src/vue/pages/LoggedInLandingPage.vue, src/vue/pages/NotLoggedInPage.vue
- Removed banners warning mobile usage.
=> DIT-424: MobileWarning.

src/vue/components/header/NavBar.vue, src/vue/components/header/PageHeader.vue, src/vue/design/override-mobile.scss
- Made header of website a different color and added a small banner based on current environment.
=> DIT-422: Environments.

src/js/modules/tooltip.js, src/vue/design/re-styles/tooltip.scss
- Added tabbing to tooltips and shows content of tooltip if tabbed to.
=> DIT-439: Hints.

src/vue/components/header/NavBar.vue
=> DIT-473: StageBanner.

src/vue/components/Banner.vue, src/vue/design/reveal.scss
- Added Firefox version of fill-available
- Added Firefox version of fill-available to Banner aswell
=> DIT-478: Browser-specific fill-available

src/vue/components/Banner.vue, src/vue/design/reveal.scss
Reverts matematikk-mooc/frontend#589
=> Revert "DIT-478: Browser-specific fill-available"

tests/canvas/build-theme.spec.js
Provide a short description about the changes.
---
Added
-   List new features, functionality
Changed
-   List changes to existing functionality
Removed
-   List features or functionality removed
Fixed
-   List features or functionality that has been fixed
---
-   [ ] Add a short description of the changes. (will be used for public changelog)
-   [ ] Fill out Added, Changed, Removed, Fixed and remove any unused lists (will be used for public changelog)
-   [ ] Make sure both security and lint tests have passed since continue-on-error is enabled.
=> FIX: Change ul to div according to canvas DOM

src/vue/design/override-base-Canvas-elements.scss
- Fixed overflowissue on new theme
- Fixed overflow for table on courses
=> DIT-477: Adminoverflow

src/vue/components/header/PageHeader.vue, src/vue/design/override-mobile.scss
=> DIT-813: Added linking to logo.

src/js/main.js, src/vue/design/override-base-Canvas-elements.scss
Regenerated missing menu for /files page
=> DIT-813: Regenerated settings menu for files page

src/js/account-theme.js
=> DIT-789: changed selector
